project:
  type: website

website:
  title: "Nhi Dinh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example.qmd
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

